#! /usr/bin/perl

################################################################################
# File Name :
#          generate_filelist.pl
#
# Version   :
#          1.0, 23-Feb-2009.
# Purpose:
#          This script is used to generate File_list.txt which is usually
#          generated by the build system at the end of the build process.
#          File_list.txt is required at the earlier stages of the build process
#          to import all the source files into the SourceInsight/CodeWright.
#
# Prerequisite:
#          1. Perl v5 or higher installed.
#          2. config.py
#
# How to Run:
#          1. Get <Root Dir>/gill_vob/6_coding in command window.
#          2. Run "perl generate_filelist.pl"
#
# Output File:
#          1. generated_File_list.txt
#
################################################################################

print "Started reading config.py...\n";

open (INFILE, "config.py") or die "Unable to open the input file!\n";
open (OUTFILE, ">generated_File_list.txt") or die "Unable to create output file!\n";

print "Generating File_list.txt...\n";

while (<INFILE>)
{
   if (m/^SourceFile/ or m/^ProjectFile/ or m/^HeaderFile/ or m/^T55File/ or m/^ModelFile/  or m/^OtherFile/  or m/^OtherheaderFile/ or m/^xmlFile/)
   {
      @temp_array = split /'/;
      $selected_var = $temp_array[1];

      # Identify config.py
      $selected_var =~ s/\(\.\*\\\.py\)\.\*/config\.py/g;

      # Skip tools files
      next if ($selected_var =~ /\$ROOT/);

      # Explore the target path for all symbolic links.
      $temp_string = `cleartool describe -fmt "%[slink_text]Tp" $selected_var`;

      if ($temp_string)
      {
         # Apply the path correction.
         $temp_string =~ s/\\/\//g;
         $temp_string =~ s/^[\.\.\/]*/\// if ($temp_string =~ /[\.\.\/]*$/);
         print OUTFILE $temp_string, "\n";
      }
      else
      {
         print OUTFILE $selected_var, "\n";
      }

   }
   else
   {
      next;
   }
}

close INFILE;
close OUTFILE;

print "File_list.txt is generated successfully...\n";
